#! /bin/sh

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ]; then mkdir work; fi

EXTRA_INCLUDES=`find ../../veins/src/ -type d | sed s!^!-I../!`
EXTRA_INCLUDES="$EXTRA_INCLUDES -I./lib "

opp_test gen $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f --deep -lveins -L../../../veins/src/ -P . --no-deep-includes $EXTRA_INCLUDES; make) || exit 1 
echoecho
opp_test run $OPT -v $TESTFILES || exit 1
echo
echo Results can be found in ./work






